require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HiveDaysController do

  # This should return the minimal set of attributes required to create a valid
  # HiveDay. As you add validations to HiveDay, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HiveDaysController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all hive_days as @hive_days" do
      hive_day = HiveDay.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hive_days).should eq([hive_day])
    end
  end

  describe "GET show" do
    it "assigns the requested hive_day as @hive_day" do
      hive_day = HiveDay.create! valid_attributes
      get :show, {:id => hive_day.to_param}, valid_session
      assigns(:hive_day).should eq(hive_day)
    end
  end

  describe "GET new" do
    it "assigns a new hive_day as @hive_day" do
      get :new, {}, valid_session
      assigns(:hive_day).should be_a_new(HiveDay)
    end
  end

  describe "GET edit" do
    it "assigns the requested hive_day as @hive_day" do
      hive_day = HiveDay.create! valid_attributes
      get :edit, {:id => hive_day.to_param}, valid_session
      assigns(:hive_day).should eq(hive_day)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HiveDay" do
        expect {
          post :create, {:hive_day => valid_attributes}, valid_session
        }.to change(HiveDay, :count).by(1)
      end

      it "assigns a newly created hive_day as @hive_day" do
        post :create, {:hive_day => valid_attributes}, valid_session
        assigns(:hive_day).should be_a(HiveDay)
        assigns(:hive_day).should be_persisted
      end

      it "redirects to the created hive_day" do
        post :create, {:hive_day => valid_attributes}, valid_session
        response.should redirect_to(HiveDay.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hive_day as @hive_day" do
        # Trigger the behavior that occurs when invalid params are submitted
        HiveDay.any_instance.stub(:save).and_return(false)
        post :create, {:hive_day => {}}, valid_session
        assigns(:hive_day).should be_a_new(HiveDay)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HiveDay.any_instance.stub(:save).and_return(false)
        post :create, {:hive_day => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hive_day" do
        hive_day = HiveDay.create! valid_attributes
        # Assuming there are no other hive_days in the database, this
        # specifies that the HiveDay created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HiveDay.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => hive_day.to_param, :hive_day => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested hive_day as @hive_day" do
        hive_day = HiveDay.create! valid_attributes
        put :update, {:id => hive_day.to_param, :hive_day => valid_attributes}, valid_session
        assigns(:hive_day).should eq(hive_day)
      end

      it "redirects to the hive_day" do
        hive_day = HiveDay.create! valid_attributes
        put :update, {:id => hive_day.to_param, :hive_day => valid_attributes}, valid_session
        response.should redirect_to(hive_day)
      end
    end

    describe "with invalid params" do
      it "assigns the hive_day as @hive_day" do
        hive_day = HiveDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HiveDay.any_instance.stub(:save).and_return(false)
        put :update, {:id => hive_day.to_param, :hive_day => {}}, valid_session
        assigns(:hive_day).should eq(hive_day)
      end

      it "re-renders the 'edit' template" do
        hive_day = HiveDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HiveDay.any_instance.stub(:save).and_return(false)
        put :update, {:id => hive_day.to_param, :hive_day => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hive_day" do
      hive_day = HiveDay.create! valid_attributes
      expect {
        delete :destroy, {:id => hive_day.to_param}, valid_session
      }.to change(HiveDay, :count).by(-1)
    end

    it "redirects to the hive_days list" do
      hive_day = HiveDay.create! valid_attributes
      delete :destroy, {:id => hive_day.to_param}, valid_session
      response.should redirect_to(hive_days_url)
    end
  end

end
